CREATE TABLE Minions(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50) NOT NULL,
	Age INT  NOT NULL CHECK(Age>0)
)

CREATE TABLE Towns(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] VARCHAR(50) NOT NULL	
)

