CREATE DATABASE Supermarket 
COLLATE Cyrillic_General_100_CI_AI


CREATE TABLE Categories (
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL
)

CREATE TABLE Items (
Id INT PRIMARY KEY IDENTITY,
[Name]  NVARCHAR(30) NOT NULL,
Price DECIMAL(15,2) NOT NULL,
CategoryId INT NOT NULL,
CONSTRAINT FK_Items_Categories FOREIGN KEY (CategoryId) REFERENCES Categories(Id)
)

CREATE TABLE Employees (
Id INT PRIMARY KEY IDENTITY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Phone CHAR(12) NOT NULL,
Salary DECIMAL(15,2) NOT NULL,
CONSTRAINT CHK_Phone CHECK(LEN(Phone)=12)
)

CREATE TABLE Orders (
Id INT PRIMARY KEY IDENTITY,
[DateTime]  DATETIME NOT NULL,
EmployeeId INT NOT NULL,
CONSTRAINT FK_Orders_Employees FOREIGN KEY (EmployeeId) REFERENCES Employees(Id)
)

CREATE TABLE OrderItems (
OrderId INT NOT NULL,
ItemId  INT NOT NULL,
Quantity INT NOT NULL,
CONSTRAINT CHK_Quantity CHECK(Quantity>=1),
CONSTRAINT PK_Order_Item PRIMARY KEY (OrderId, ItemId),
CONSTRAINT FK_OrderItems_Order FOREIGN KEY (OrderId) REFERENCES Orders(Id),
CONSTRAINT FK_OrderItems_Items FOREIGN KEY (ItemId) REFERENCES Items(Id)
)

CREATE TABLE Shifts (
Id INT IDENTITY NOT NULL,
EmployeeId INT,
CheckIn DATETIME NOT NULL,
CheckOut DATETIME NOT NULL,
CONSTRAINT CHK_CheckOUt CHECK(CheckOut>=CheckIn), 
CONSTRAINT PK_Shifts_Employees PRIMARY KEY (Id, EmployeeId),
CONSTRAINT FK_Shifts_Employees FOREIGN KEY (EmployeeId) REFERENCES Employees(Id)
)
