CREATE DATABASE OnlineStoreDB
COLLATE Cyrillic_General_100_CI_AI

USE OnlineStoreDB

CREATE TABLE ItemTypes(
ItemTypeId INT PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL
)


CREATE TABLE Cities(
CityId INT PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL
)


CREATE TABLE Items(
ItemId INT PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL,
ItemTypeId INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeId)
)

CREATE TABLE Customers(
CustomerId INT PRIMARY KEY IDENTITY,
Name VARCHAR(50) NOT NULL,
Birthday DATE ,
CityId INT FOREIGN KEY REFERENCES Cities(CityId)
)


CREATE TABLE Orders(
OrderId INT PRIMARY KEY IDENTITY,
CustomerId INT FOREIGN KEY REFERENCES Customers(CustomerId)
)


CREATE TABLE OrderItems(
OrderId INT,
ItemId INT,

CONSTRAINT PK_OrderItem PRIMARY KEY(OrderId,ItemId),
CONSTRAINT FK_OrderID FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
CONSTRAINT FK_ItemID FOREIGN KEY (ItemId) REFERENCES Items(ItemId)
)

