ALTER TABLE Users
DROP PK_Users

ALTER TABLE Users
ADD CONSTRAINT PK_ID PRIMARY KEY (ID);

ALTER TABLE Users
ADD CONSTRAINT uq_Username
UNIQUE (Username)

ALTER TABLE Users
ADD CONSTRAINT Userrname_Len_2 CHECK(LEN(Username)>2)
